### PR TITLE
Fix plugin for blender 4.4+

### PR DESCRIPTION
**Pull request by morrisoran**
fix __init__ to make plugin work on blender 4.4+

### CODE REVIEW

**Comment by IfArtSchoolSaysNeinEuropeWillbeMein** [comment]
I signed up  Github just to say thank you!

**Comment by RustFoxrel** [comment]
Python: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.5\scripts\addons\spring_bones (1).py", line 679, in execute
    for i, l in enumerate(data_bone.layers):
                          ^^^^^^^^^^^^^^^^
AttributeError: 'Bone' object has no attribute 'layers'

bro

**Comment by morrisoran** [comment]
> Python: Traceback (most recent call last): File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.5\scripts\addons\spring_bones (1).py", line 679, in execute for i, l in enumerate(data_bone.layers): ^^^^^^^^^^^^^^^^ AttributeError: 'Bone' object has no attribute 'layers'
> 
> bro

Armature layers is the thing that was before bone collections (prior to ~4.0). Judging by the code (i am not the dev of the addon) this function is only for switching to collider bone. This one is not functionally most important imo, because colliders works fine without using it.

It is possible to fix it for bone collections, but I need to dig up into old references, because I don't remember how armature layers worked.

**Comment by SpringBonesReviver** [comment]
Hi, I have an updated version that works perfectly with Blender 5.0.
[spring_bones.py](https://github.com/user-attachments/files/26176334/spring_bones.py)

**Comment by artellblender** [comment]
thanks but closing, the new update now supports Blender 5

**Comment by artellblender** [comment]
close

**Comment by morrisoran** [comment]
> thanks but closing, the new update now supports Blender 5

no problem, it was mainly for those who are seeked for solution when it was not working 👍
